export const Types = {
  normal: require('../../../assets/types/normal.png'),
  fighting: require('../../../assets/types/fighting.png'),
  flying: require('../../../assets/types/flying.png'),
  poison: require('../../../assets/types/poison.png'),
  ground: require('../../../assets/types/ground.png'),
  rock: require('../../../assets/types/rock.png'),
  bug: require('../../../assets/types/bug.png'),
  ghost: require('../../../assets/types/ghost.png'),
  steel: require('../../../assets/types/steel.png'),
  fire: require('../../../assets/types/fire.png'),
  water: require('../../../assets/types/water.png'),
  grass: require('../../../assets/types/grass.png'),
  electric: require('../../../assets/types/electric.png'),
  psychic: require('../../../assets/types/psychic.png'),
  ice: require('../../../assets/types/ice.png'),
  dragon: require('../../../assets/types/fire.png'),
  dark: require('../../../assets/types/dark.png'),
  fairy: require('../../../assets/types/fairy.png'),
};
